### ISSUE TITLE
Applet doesn't work on latest Cinnamon 2.3

### ISSUE THREAD

**Issue by collinss** [jonbrett/cinnamon-feeds-applet#48]
It's having trouble parsing the ```feedreader.js``` file. I think this may be due to some recent changes in cjs, but I'm not sure.

**Comment by OrangeShark** [comment]
I looked into the problem and managed to fix the parser errors in `feedreader.js`, which has to do with `..` being used instead of `.`, as well as a bunch of code related to atom which doesn't seem to be valid JavaScript. The other problem is a good chunk of the code in `feedreader.js` has been deprecated including the `XML` object and was likely removed from the JavaScript engine by mozilla, [see here](https://developer.mozilla.org/en-US/docs/Archive/Web/E4X). An alternative is to use libxml2 but I am not sure if that even works properly. I looked at other applets and desklets to see if they use xml, one of them uses a JavaScript XML library called [marknote](https://github.com/tipichris/bbcwx/blob/master/marknote.js). I will wait for more comments on whether we should pursue using markntote in the applet.

**Comment by jonbrett** [comment]
I knew that XML support in Javascript was old, but not that it was now gone! I would prefer to use the native support over using an external library if possible, but if you want to port to marknote then I wouldn't object too much.

@OrangeShark Perhaps you could point at the changes you made to feedreader.js to get it working.

**Comment by OrangeShark** [comment]
@jonbrett Alright, I sent the pull request so people can look at it here #49. It will currently run without any errors, but of course it won't be ablse to parse any feeds.

**Comment by jonbrett** [comment]
Thanks for sharing the branch. I can see what you've done there to get things to load, but seeing as it doesn't work... :(

BTW, all the strange syntax like the `..` ((grand)child) and `::` (namespace) operators are valid E4X. I guess it was a little weird that they were natively supported in the script (perhaps that's why E4X was deprecated!)

**Comment by jonbrett** [comment]
Having looked briefly a Marknote I don't think porting to marknote would be a big deal. I may give it a shot

**Comment by OrangeShark** [comment]
> BTW, all the strange syntax like the .. ((grand)child) and :: (namespace) operators are valid E4X. I guess it was a little weird that they were natively supported in the script (perhaps that's why E4X was deprecated!)

I figured. 

I looked into libxml2 and it does seem like it is not properly implemented in gjs. Only a couple of properties are exposed but are not useful, including a `dummy` property. So unless someone actually fixes it in gjs, marknote or some other JS xml library would need to be used.

**Comment by collinss** [comment]
You could use some of the code introduced with the new search providers which was implemented recently in master. It probably won't be available until Cinnamon 2.6, but it would allow you to write a python script that would parse the xml, and then pass it back to the applet using dbus. Most of the work seems to be done already on the Cinnamon end so you would just need to call the ```Util.spawn_async``` function, and pass it the command to launch the python script and the callback to handle the data when it comes in. You could check out https://github.com/linuxmint/Cinnamon/commit/a1639083e2ae2f55cc25d4534216145ef3f11feb and https://github.com/linuxmint/Cinnamon/commit/e85fb0a6b6fa700447ab4b558769a1ae5dcace3e to see the code and some examples.

**Comment by lestcape** [comment]
I really agree with the @collinss idea, for one important reason... The performance of running all hardest task out of the compositor thread of cinnamon (like download the info). But will be complex rewrite the applet again on other languages, and could create a problem if it's need some python dependencies...

**Comment by lestcape** [comment]
The recommended solution by gnome devs, is to used Gxml https://github.com/GNOME/gxml, but this have a low support actually on all distros...

**Comment by lestcape** [comment]
https://github.com/jonbrett/cinnamon-feeds-applet/pull/50

**Comment by mockturtl** [comment]
+1 (2.6/betsy)
